//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatorUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title:
        ///0x02=0xB8B8E8:Light Blue
        ///0x03=0xF88C14:Orange
        ///0x04=0xFFFFFF:White
        ///0x05=0x847474:Grey
        ///0x06=0x088008:Green
        ///0x0D=0xB8B8E8:Light Blue
        ///0x1A=0xB8B8E8:Light Blue
        ///
        ///briefing:
        ///0x02=0xB8B8E8:Light Blue
        ///0x03=0x088008:Green
        ///0x04=0xACF46C:Light Green
        ///0x05=0x847474:Grey
        ///0x06=0xFFFFFF:White
        ///0x07=0xF40404:Red (p1)
        ///0x0D=0xB8B8E8:Light Blue
        ///0x1A=0xB8B8E8:Light Blue
        ///
        ///game:
        ///0x01=0xB8B8E8:Use Default
        ///0x02=0xB8B8E8:Cyan
        ///0x03=0xDCDC3C:Yellow
        ///0x04=0xFFFFFF:White
        ///0x05=0x847474:Grey
        ///0x06=0xC81818:Red
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EPPlus {
            get {
                object obj = ResourceManager.GetObject("EPPlus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TranslateLib {
            get {
                object obj = ResourceManager.GetObject("TranslateLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
